import { Toaster } from "sonner";
import { getMyCurriculum } from "@/app/actions/curriculum-actions";
import { StudentNav } from "@/components/student/student-nav";
import { MufredatClient } from "./mufredat-client";

export const metadata = {
  title: "Müfredat Takip",
  description: "Generated by Next.js",
};

export default async function MufredatPage() {
  const result = await getMyCurriculum();

  return (
    <main className="min-h-screen bg-gray-50 px-4 py-8">
      <div className="mx-auto w-full max-w-md">
        <StudentNav />

        <header className="mb-6">
          <h1 className="text-xl font-bold text-gray-900">Müfredat Takip</h1>
          <p className="mt-1 text-sm text-gray-500">
            Konuları işleme durumuna göre güncelle: başlamadı, çalışılıyor veya
            bitti.
          </p>
        </header>

        {result.success === false ? (
          <div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-medium text-red-700">
            {result.message}
          </div>
        ) : (
          <MufredatClient snapshot={result.data} />
        )}
      </div>

      <Toaster position="top-center" richColors />
    </main>
  );
}